"""
=============================================================================
IDX Quantitative Scalping Engine — Main Orchestrator (S.E.A. v6.0)
Version       : 2026.Q3.v28.1 (S.E.A. Master — Dynamic Module Loading)
Compliance    : Indonesia Stock Exchange (IDX) — Fail-Closed Safety
Architecture  : S.E.A. (sea.py) is the SINGLE SOURCE OF TRUTH (SSOT).
               main.py is a passive executor that dynamically loads all modules
               from S.E.A. memory (generated/evolved by AI).
=============================================================================
"""

from __future__ import annotations

import os
import sys
import json
import argparse
import logging
import traceback
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np
import polars as pl

WIB_TZ = ZoneInfo("Asia/Jakarta")

# ========================== DYNAMIC MODULE LOADER (S.E.A.) ==========================
# sea_loader must be present and provide:
#   - set_agent(agent)
#   - load_module_dynamically(module_name)
try:
    from sea_loader import set_agent, load_module_dynamically
    HAS_SEA_LOADER = True
except ImportError:
    set_agent = None  # type: ignore
    load_module_dynamically = None  # type: ignore
    HAS_SEA_LOADER = False
    print("❌ ERROR: sea_loader.py not found. Please create it first.")
    sys.exit(1)

# ========================== S.E.A. AGENT (sea.py) ==========================
try:
    from sea import GodEntity, VERSION as AGENT_VERSION
    HAS_SEA = True
except ImportError:
    GodEntity = None  # type: ignore
    AGENT_VERSION = "0.0.0"
    HAS_SEA = False
    print("❌ ERROR: sea.py not found. Please place it in the project root.")
    sys.exit(1)

# ========================== STATIC MODULES (only data loader, logger, etc.) ==========================
# These modules are NOT generated by S.E.A. because they are infrastructure.
try:
    from data import load_and_prepare_market_data, sanitize_ticker_list, DataLoader
    HAS_DATA = True
except ImportError:
    load_and_prepare_market_data = None  # type: ignore
    sanitize_ticker_list = None  # type: ignore
    DataLoader = None  # type: ignore
    HAS_DATA = False
    print("⚠️ WARNING: data.py not found. Market data loading will fail.")

try:
    from logger import get_logger
    logger = get_logger("IDX.Main")
except ImportError:
    logging.basicConfig(level=logging.INFO, format="[%(asctime)s] [%(levelname)s] %(name)s: %(message)s")
    logger = logging.getLogger("IDX.Main")

# ========================== CONSTANTS ==========================
SIMULATION_ONLY: bool = True
PORTFOLIO_STATE_FILE: str = "portfolio_state.json"
DEFAULT_BLUECHIP_UNIVERSE = [
    "BBCA.JK", "BBRI.JK", "BMRI.JK", "BBNI.JK", "TLKM.JK",
    "ASII.JK", "UNVR.JK", "ICBP.JK", "INDF.JK", "GOTO.JK",
]
DEFAULT_UNIVERSE_FILE = "universe.json"
DEFAULT_MODEL_PATH = "models/idx_scalping_model.joblib"

HORIZON_DAYS = {"SHORT": 1, "MEDIUM": 5, "LONG": 20}
VALID_HORIZONS = ("SHORT", "MEDIUM", "LONG")


def normalize_horizon(raw) -> str:
    if raw is None:
        return "SHORT"
    s = str(raw).strip().upper()
    if s in VALID_HORIZONS:
        return s
    try:
        d = float(s)
        if d <= 2:
            return "SHORT"
        if d <= 10:
            return "MEDIUM"
        return "LONG"
    except Exception:
        return "SHORT"


# ========================== ORCHESTRATOR ==========================
class ProductionOrchestrator:
    """
    Passive executor. All decision-making modules (risk, features, portfolio, etc.)
    are dynamically loaded from S.E.A. memory (generated/evolved by AI).
    """

    def __init__(self, dry_run: bool = True, self_learning: bool = False, enable_self_evolving: bool = False) -> None:
        self.dry_run = True
        self.self_learning_flag = bool(self_learning)
        self.enable_self_evolving = bool(enable_self_evolving)
        self.api_key = (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY") or "").strip()

        # Configuration will be provided by S.E.A.
        self.trading_config: Dict[str, Any] = {}

        # Data containers
        self.universe: List[str] = []
        self.market_data: pl.DataFrame = pl.DataFrame()
        self.features_data: pl.DataFrame = pl.DataFrame()
        self.predictions_data: pl.DataFrame = pl.DataFrame()
        self.signals_data: pl.DataFrame = pl.DataFrame()
        self.orders: List[Dict[str, Any]] = []
        self.portfolio_state: Dict[str, Any] = {}
        self.risk_output: Any = None
        self.execution_id = datetime.now(WIB_TZ).strftime("%Y%m%d_%H%M%S")

        # Engines (will be dynamically loaded)
        self.ml_engine = None
        self.signal_engine = None
        self.risk_engine = None
        self.portfolio_engine = None
        self.storage_engine = None

        # ======================== S.E.A. AGENT INIT (FULL AUTHORITY) ========================
        self.self_evolving_agent = None
        if self.enable_self_evolving and HAS_SEA and GodEntity is not None:
            project_root = os.getcwd()
            self.self_evolving_agent = GodEntity(base_dir=project_root)
            # Inject agent into the dynamic loader
            if HAS_SEA_LOADER and set_agent is not None:
                set_agent(self.self_evolving_agent)
            logger.info(
                f"🤖 [SEA_MASTER] sea.py v{AGENT_VERSION} initialized "
                f"with FULL AUTHORITY over project root: {project_root}"
            )
        elif self.enable_self_evolving:
            logger.warning("⚠️ sea.py (GodEntity) not available — disable --enable-self-evolving")

        # Generate/load necessary modules from S.E.A.
        self._ensure_modules()

        self._log_module_matrix()

    def _ensure_modules(self) -> None:
        """Ensure all required modules exist in S.E.A. memory; generate if missing."""
        if not self.self_evolving_agent:
            return
        required_modules = ["risk", "features", "portfolio", "prediction", "signal_idx"]
        for mod in required_modules:
            code = self.self_evolving_agent.memory.get_module_code(mod)
            if not code:
                logger.info(f"🧠 [SEA] Generating module '{mod}' for the first time...")
                self.self_evolving_agent.generate_module_code(mod)

    def _log_module_matrix(self) -> None:
        matrix = {
            "data": HAS_DATA,
            "sea (agent)": HAS_SEA,
            "sea_loader": HAS_SEA_LOADER,
        }
        # Add dynamically loaded modules
        if self.self_evolving_agent:
            for mod in ["risk", "features", "portfolio", "prediction", "signal_idx"]:
                code = self.self_evolving_agent.memory.get_module_code(mod)
                matrix[mod] = bool(code)
        online = sum(1 for v in matrix.values() if v)
        logger.info(f"📦 [MODULE_MATRIX] {online}/{len(matrix)} online → {matrix}")

    # ========================== PIPELINE STEPS ==========================

    def _step_0_sea_awaken(self) -> None:
        logger.info("▶ [STEP 0] S.E.A. Master Entity awaken")
        if self.self_evolving_agent:
            try:
                self.self_evolving_agent.boot()
                logger.info("🧠 [SEA_MASTER] GodEntity booted successfully.")
            except Exception as e:
                logger.warning(f"⚠️ [SEA_MASTER] Boot failed: {e}")
        else:
            logger.warning("⚠️ [SEA_MASTER] Agent disabled. Using isolated defaults.")

    def _step_1_universe(self) -> None:
        logger.info("▶ [STEP 1] Universe sync")
        if os.path.isfile(DEFAULT_UNIVERSE_FILE):
            try:
                with open(DEFAULT_UNIVERSE_FILE, encoding="utf-8") as f:
                    raw = json.load(f)
                if isinstance(raw, list):
                    self.universe = sanitize_ticker_list(raw) if HAS_DATA else raw
                elif isinstance(raw, dict):
                    self.universe = sanitize_ticker_list(raw.get("tickers") or raw.get("universe") or []) if HAS_DATA else []
            except Exception as e:
                logger.warning(f"⚠️ universe.json read failed: {e}")
        if not self.universe:
            self.universe = sanitize_ticker_list(DEFAULT_BLUECHIP_UNIVERSE) if HAS_DATA else DEFAULT_BLUECHIP_UNIVERSE
            logger.info(f"ℹ️ Using default bluechip universe ({len(self.universe)} tickers)")
        logger.info(f"✔ Universe size={len(self.universe)}")

    def _step_2_data(self) -> None:
        logger.info("▶ [STEP 2] Data layer")
        if not HAS_DATA:
            logger.error("❌ data.py not available. Cannot load market data.")
            return
        try:
            result = load_and_prepare_market_data(symbols=self.universe, use_cache=True)
            if isinstance(result, pl.DataFrame):
                self.market_data = result
            elif isinstance(result, dict) and "data" in result:
                self.market_data = result["data"]
            else:
                self.market_data = pl.DataFrame()
            logger.info(f"✔ Market data rows={self.market_data.height} cols={self.market_data.width}")
        except Exception as e:
            logger.error(f"❌ [STEP_2] Data load failed: {e}")
            self.market_data = pl.DataFrame()

    def _step_3_sea_config(self) -> None:
        logger.info("▶ [STEP 3] S.E.A. Master proposes trading config → hard clamp")
        if self.self_evolving_agent:
            try:
                proposed = self.self_evolving_agent.propose_trading_config()
                self.trading_config = proposed  # S.E.A. already applies clamps
                self.self_evolving_agent.memory.set("trading_config", self.trading_config)
            except Exception as e:
                logger.error(f"❌ [STEP 3] Agent config proposal failed: {e}")
                self.trading_config = {
                    "min_adtv_idr": 5_000_000_000.0,
                    "min_confidence": 0.72,
                    "min_rrr": 1.20,
                    "risk_scale": 0.20,
                    "configured_by": "FALLBACK"
                }
        else:
            logger.warning("⚠️ [STEP 3] Agent disabled. Using fallback defaults.")
            self.trading_config = {
                "min_adtv_idr": 5_000_000_000.0,
                "min_confidence": 0.72,
                "min_rrr": 1.20,
                "risk_scale": 0.20,
                "configured_by": "FALLBACK"
            }
        logger.info(f"🤖 [CONFIG] {self.trading_config}")

    def _step_4_features(self) -> None:
        logger.info("▶ [STEP 4] Feature engineering")
        if self.market_data.height == 0:
            logger.warning("⚠️ Skip features — empty market data")
            return
        # Load features module dynamically from S.E.A.
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                features_mod = load_module_dynamically("features")
                if hasattr(features_mod, "UnifiedFeatureEngine"):
                    eng = features_mod.UnifiedFeatureEngine(sea_agent=self.self_evolving_agent)
                    if hasattr(eng, "transform"):
                        self.features_data = eng.transform(self.market_data)
                    elif hasattr(eng, "build"):
                        self.features_data = eng.build(self.market_data)
                    else:
                        self.features_data = self.market_data
                    logger.info(f"✔ Features rows={self.features_data.height}")
                    return
            except Exception as e:
                logger.warning(f"⚠️ Dynamic features loading failed: {e}")
        # Fallback: use market data as features
        self.features_data = self.market_data
        logger.info("ℹ️ Features: using raw market data as fallback")

    def _step_5_ml(self) -> None:
        logger.info("▶ [STEP 5] Machine learning predict+calibrate")
        src = self.features_data if self.features_data.height else self.market_data
        if src.height == 0:
            logger.warning("⚠️ Skip ML — no data")
            return
        # Try dynamic ML module
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                ml_mod = load_module_dynamically("machine_learning")
                if hasattr(ml_mod, "UnifiedModelEngine"):
                    if self.ml_engine is None:
                        self.ml_engine = ml_mod.UnifiedModelEngine(sea_agent=self.self_evolving_agent)
                    if hasattr(self.ml_engine, "predict_and_calibrate"):
                        self.predictions_data = self.ml_engine.predict_and_calibrate(src)
                        logger.info(f"✔ Predictions rows={self.predictions_data.height}")
                        return
            except Exception as e:
                logger.warning(f"⚠️ Dynamic ML loading failed: {e}")
        # Fallback: build rule-based from features (if available)
        self._build_rule_based_from_features()

    def _build_rule_based_from_features(self) -> None:
        """Deterministic fallback if ML not available."""
        src = self.features_data if self.features_data.height else self.market_data
        if src.height == 0:
            self.predictions_data = pl.DataFrame()
            return
        # Simple rule: RSI > 50 + MACD > 0 → BUY (just placeholder)
        try:
            # Basic indicators if columns exist
            if "rsi_14" in src.columns and "macd_hist" in src.columns:
                cond = (pl.col("rsi_14") > 50) & (pl.col("macd_hist") > 0)
                filtered = src.filter(cond)
                if filtered.height > 0:
                    self.predictions_data = filtered.with_columns([
                        pl.lit("BUY").alias("candidate_signal"),
                        pl.lit(0.65).alias("prediction_probability"),
                        pl.lit("MODEL_NOT_READY").alias("model_status"),
                        pl.lit("RULE_BASED").alias("signal_source"),
                    ])
                    logger.info(f"✔ Rule-based predictions rows={self.predictions_data.height}")
                    return
        except Exception as e:
            logger.warning(f"Rule-based fallback failed: {e}")
        self.predictions_data = pl.DataFrame()

    def _step_6_prediction_engine(self) -> None:
        logger.info("▶ [STEP 6] Prediction engine (TP/SL/regime/rank)")
        src = self.predictions_data if self.predictions_data.height else self.features_data
        if src.height == 0:
            return
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                pred_mod = load_module_dynamically("prediction")
                if hasattr(pred_mod, "UnifiedPredictionEngine"):
                    eng = pred_mod.UnifiedPredictionEngine(sea_agent=self.self_evolving_agent)
                    if hasattr(eng, "run_prediction_pipeline"):
                        out = eng.run_prediction_pipeline(src)
                        if isinstance(out, pl.DataFrame) and out.height:
                            self.predictions_data = out
                            logger.info(f"✔ Prediction engine rows={out.height}")
                            return
            except Exception as e:
                logger.warning(f"⚠️ Dynamic prediction loading failed: {e}")
        logger.info("ℹ️ Prediction engine skipped (no dynamic module)")

    def _step_7_sea_analysis(self) -> None:
        logger.info("▶ [STEP 7] S.E.A. Master deep-dive top candidates")
        src = self.predictions_data if self.predictions_data.height else pl.DataFrame()
        if src.height == 0 or not self.self_evolving_agent:
            return
        try:
            cols = [c for c in ("ticker", "asset", "prediction_probability", "probability", "close", "raw_score") if c in src.columns]
            head = src.select(cols).head(10) if cols else src.head(10)
            report = head.write_csv() if hasattr(head, "write_csv") else str(head)
            analysis = self.self_evolving_agent.analyze_candidates_deep(report)
            if analysis:
                logger.info(f"🧠 [SEA_ANALYSIS] {str(analysis)[:500]}")
        except Exception as e:
            logger.warning(f"⚠️ Candidate analysis soft-fail: {e}")

    def _step_8_signals(self) -> None:
        logger.info("▶ [STEP 8] Signal gateway pipeline")
        src = self.predictions_data
        if src is None or src.height == 0:
            logger.info("ℹ️ No predictions → NO_SIGNAL")
            self.signals_data = pl.DataFrame()
            self.orders = []
            return
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                sig_mod = load_module_dynamically("signal_idx")
                if hasattr(sig_mod, "UnifiedSignalEngine"):
                    init_kwargs = {
                        "custom_configs": {
                            "generator": {
                                "min_24h_volume_idr": float(self.trading_config.get("min_adtv_idr", 5e9)),
                                "min_risk_reward_ratio": float(self.trading_config.get("min_rrr", 1.2)),
                            },
                            "confidence": {
                                "min_prediction_confidence": float(self.trading_config.get("min_confidence", 0.72)),
                            }
                        }
                    }
                    try:
                        self.signal_engine = sig_mod.UnifiedSignalEngine(**init_kwargs, sea_agent=self.self_evolving_agent)
                    except TypeError:
                        self.signal_engine = sig_mod.UnifiedSignalEngine(**init_kwargs)
                    if hasattr(self.signal_engine, "execute_pipeline"):
                        self.signals_data = self.signal_engine.execute_pipeline(src, run_ai_diagnostics=True)
                    elif hasattr(self.signal_engine, "generate_signals"):
                        self.signals_data = self.signal_engine.generate_signals(src)
                    else:
                        self.signals_data = pl.DataFrame()
                    self.orders = self._signals_to_orders(self.signals_data)
                    logger.info(f"✔ Signals rows={getattr(self.signals_data, 'height', 0)} orders={len(self.orders)}")
                    return
            except Exception as e:
                logger.error(f"❌ Signal pipeline failed: {e}")
        # Fallback: convert predictions directly
        self.orders = self._predictions_to_orders(src)

    def _step_9_risk(self) -> None:
        logger.info("▶ [STEP 9] Risk engine")
        src = self.market_data if self.market_data.height else self.predictions_data
        if src.height == 0:
            return
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                risk_mod = load_module_dynamically("risk")
                if hasattr(risk_mod, "UnifiedRiskEngine"):
                    self.risk_engine = risk_mod.UnifiedRiskEngine(sea_agent=self.self_evolving_agent)
                    if hasattr(self.risk_engine, "evaluate_market_risk"):
                        self.risk_output = self.risk_engine.evaluate_market_risk(
                            src,
                            pipeline_timestamp=datetime.now(timezone.utc).isoformat(),
                            execution_id=self.execution_id,
                        )
                        logger.info(f"✔ Risk evaluated: {type(self.risk_output).__name__}")
                        return
            except Exception as e:
                logger.warning(f"⚠️ Risk soft-fail: {e}")
        logger.info("ℹ️ Risk engine skipped (dynamic module unavailable)")

    def _step_10_portfolio_simulation(self) -> None:
        logger.info("▶ [STEP 10] Portfolio simulation sync (SIMULATION_ONLY)")
        latest_prices = self._latest_prices_from_market()
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                port_mod = load_module_dynamically("portfolio")
                if hasattr(port_mod, "UnifiedPortfolioEngine"):
                    try:
                        self.portfolio_engine = port_mod.UnifiedPortfolioEngine(
                            config={"dry_run": True, "simulation_only": True},
                            state_file=PORTFOLIO_STATE_FILE,
                            sea_agent=self.self_evolving_agent,
                        )
                    except TypeError:
                        self.portfolio_engine = port_mod.UnifiedPortfolioEngine(
                            config={"dry_run": True, "simulation_only": True},
                            state_file=PORTFOLIO_STATE_FILE,
                        )
                    if hasattr(self.portfolio_engine, "load_portfolio_state"):
                        try:
                            loaded = self.portfolio_engine.load_portfolio_state()
                            if isinstance(loaded, dict) and loaded:
                                self.portfolio_state = loaded
                                logger.info(f"✔ Portfolio state LOADED | positions={len(loaded.get('positions', {}))}")
                        except Exception as e:
                            logger.warning(f"⚠️ load_portfolio_state: {e}")
                    # Process signals
                    if self.orders and hasattr(self.portfolio_engine, "process_trading_signals"):
                        try:
                            result = self.portfolio_engine.process_trading_signals(
                                self.orders,
                                latest_prices=latest_prices,
                                top_n=len(self.orders)
                            )
                            if isinstance(result, dict):
                                self.portfolio_state = {**self.portfolio_state, **result}
                            logger.info(f"✔ process_trading_signals OK orders={len(self.orders)}")
                        except Exception as e:
                            logger.warning(f"⚠️ process_trading_signals: {e}")
                    # Save
                    if hasattr(self.portfolio_engine, "save_portfolio_state"):
                        try:
                            self.portfolio_engine.save_portfolio_state()
                            logger.info(f"✅ Portfolio state SAVED → {PORTFOLIO_STATE_FILE}")
                        except Exception as e:
                            logger.warning(f"⚠️ save_portfolio_state: {e}")
                    # TP/SL monitoring
                    self._apply_simulated_tpsl_exits(latest_prices)
                    return
            except Exception as e:
                logger.warning(f"⚠️ Portfolio engine soft-fail: {e}")
        # Fallback: minimal portfolio state
        self.portfolio_state = {
            "equity": 10_000_000.0,
            "cash": 10_000_000.0,
            "positions": {},
            "return_pct": 0.0,
            "exposure_pct": 0.0,
            "mode": "simulation",
            "simulation_only": True,
        }

    def _step_11_storage(self) -> None:
        logger.info("▶ [STEP 11] Persist signals/predictions")
        # Try dynamic storage
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                storage_mod = load_module_dynamically("storage")
                if hasattr(storage_mod, "UnifiedStorageEngine"):
                    self.storage_engine = storage_mod.UnifiedStorageEngine(sea_agent=self.self_evolving_agent)
                    if self.signals_data is not None and self.signals_data.height:
                        if hasattr(self.storage_engine, "persist_signals"):
                            self.storage_engine.persist_signals(self.signals_data)
                    if self.predictions_data is not None and self.predictions_data.height:
                        if hasattr(self.storage_engine, "persist_predictions"):
                            self.storage_engine.persist_predictions(self.predictions_data)
                    logger.info("✔ Storage step done")
                    return
            except Exception as e:
                logger.warning(f"⚠️ Storage soft-fail: {e}")
        logger.info("ℹ️ Storage skipped (dynamic module unavailable)")

    def _step_12_sea_telegram(self) -> None:
        logger.info("▶ [STEP 12] S.E.A. Master narrates & broadcasts")
        token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
        chat_id = os.getenv("TELEGRAM_CHAT_ID", "").strip()
        if not token or not chat_id:
            logger.warning("⚠️ TELEGRAM secrets unset — skip send")
            return
        narrative = self.self_evolving_agent.narrate_market(self.portfolio_state, top_signals=self.orders[:5] if self.orders else None) if self.self_evolving_agent else "No narrative"
        logger.info(f"🗞️ [NARRATIVE] {narrative[:300]}")
        # Try dynamic reporting
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                report_mod = load_module_dynamically("reporting")
                if hasattr(report_mod, "UnifiedReportingEngine"):
                    engine = report_mod.UnifiedReportingEngine(
                        config={
                            "TELEGRAM_BOT_TOKEN": token,
                            "TELEGRAM_CHAT_ID": chat_id,
                            "REPORTING_MIN_CONFIDENCE": float(self.trading_config.get("min_confidence", 0.72)),
                            "INITIAL_CAPITAL_IDR": float(self.portfolio_state.get("equity", 10_000_000.0)),
                            "MARKET_NARRATIVE": narrative,
                        },
                        mode="dry_run",
                    )
                    if hasattr(engine, "send_telegram_broadcast"):
                        ok = engine.send_telegram_broadcast(
                            orders=self.orders if self.orders else None,
                            portfolio_data=self.portfolio_state,
                        )
                        logger.info(f"{'✅' if ok else '⚠️'} Telegram result={ok}")
                        return
            except Exception as e:
                logger.warning(f"⚠️ Telegram soft-fail: {e}")
        logger.info("ℹ️ Telegram broadcast skipped (dynamic reporting unavailable)")

    def _step_13_monitoring_eval(self) -> None:
        logger.info("▶ [STEP 13] Monitoring / evaluation hooks")
        # Try dynamic monitoring
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                mon_mod = load_module_dynamically("monitoring")
                if hasattr(mon_mod, "UnifiedMonitoringEngine"):
                    mon = mon_mod.UnifiedMonitoringEngine(sea_agent=self.self_evolving_agent)
                    if hasattr(mon, "execute_full_audit"):
                        try:
                            mon.execute_full_audit()
                        except Exception as e:
                            logger.info(f"ℹ️ Monitoring audit soft-skip: {e}")
                    logger.info(f"✔ Monitoring engine: {type(mon).__name__}")
            except Exception as e:
                logger.warning(f"⚠️ Monitoring soft-fail: {e}")

    def _step_14_self_learning(self) -> None:
        logger.info("▶ [STEP 14] Self-learning / adaptation")
        always = os.getenv("IDX_ALWAYS_LEARN", "").strip() in ("1", "true", "True", "yes")
        do_full = bool(self.self_learning_flag or always)
        # Log feedback
        try:
            os.makedirs("storage", exist_ok=True)
            feedback = {
                "ts": datetime.now(WIB_TZ).isoformat(),
                "execution_id": self.execution_id,
                "n_orders": len(self.orders),
                "trading_config": self.trading_config,
                "portfolio_equity": self.portfolio_state.get("equity"),
                "simulation_only": True,
            }
            with open("storage/learning_feedback.jsonl", "a", encoding="utf-8") as f:
                f.write(json.dumps(feedback, default=str) + "\n")
            logger.info("✔ [LEARN_LIGHT] feedback snapshot appended")
        except Exception as e:
            logger.warning(f"⚠️ light feedback log failed: {e}")
        if not do_full:
            logger.info("ℹ️ Full self-learning deferred (use --self-learning)")
            return
        if HAS_SEA_LOADER and load_module_dynamically is not None:
            try:
                learn_mod = load_module_dynamically("self_learning")
                if hasattr(learn_mod, "UnifiedSelfLearningEngine"):
                    eng = learn_mod.UnifiedSelfLearningEngine(sea_agent=self.self_evolving_agent)
                    for method in ("run", "adapt", "learn", "run_adaptation_cycle"):
                        if hasattr(eng, method):
                            try:
                                getattr(eng, method)()
                                logger.info(f"✔ Self-learning via .{method}()")
                                break
                            except Exception as e:
                                logger.warning(f"⚠️ self-learning {method}: {e}")
            except Exception as e:
                logger.warning(f"⚠️ Self-learning soft-fail: {e}")

    def _step_15_autonomous_agent(self) -> None:
        if not self.enable_self_evolving or self.self_evolving_agent is None:
            logger.info("▶ [STEP 15] Autonomous agent disabled (use --enable-self-evolving)")
            return
        logger.info("▶ [STEP 15] S.E.A. Master with FULL AUTHORITY over all modules")
        try:
            agent = self.self_evolving_agent
            if not getattr(agent, "_booted", False):
                agent.boot()
            obs = agent.observe()
            goal = (
                f"Execute deep quantitative trading analysis, optimize the IDX scalping engine, "
                f"and self-evolve (execution_id={self.execution_id}). "
                f"You have FULL AUTHORITY to modify sea.py, main.py, and all dynamically "
                f"loaded modules (risk, features, portfolio, etc.). "
                f"Optimize the entire system based on objective trading metrics (profit, Sharpe, speed, memory)."
            )
            agent.set_goal(goal)
            plan = agent.plan(goal)
            agent.memory.set("last_trading_execution_id", self.execution_id)
            agent.memory.set("last_trading_observation", obs)
            agent.memory.set("last_trading_plan", plan)
            logger.info(f"🔎 [AUTONOMOUS] Observation files={obs.get('repository', {}).get('file_count')}")
            logger.info(f"🧠 [AUTONOMOUS] Plan tasks={len(plan.get('tasks', []))}")
            logger.warning("⚡ [AUTONOMOUS] Full authority mode ACTIVE — agent may evolve all modules.")
            max_iter = int(os.getenv("AGENT_MAX_ITERATIONS", "5"))
            result = agent.run_loop(max_iterations=max_iter)
            logger.info(f"⚡ [AUTONOMOUS] Evolution loop completed: iterations={result.get('iterations')}")
            agent.memory.set("last_evolution_result", result)
        except Exception as e:
            logger.warning(f"⚠️ [STEP 15] Autonomous agent soft-fail: {e}")

    # ========================== HELPERS ==========================

    def _predictions_to_orders(self, df: pl.DataFrame) -> List[Dict[str, Any]]:
        orders: List[Dict[str, Any]] = []
        if df is None or df.height == 0:
            return orders
        min_conf = float(self.trading_config.get("min_confidence", 0.72))
        min_rrr = float(self.trading_config.get("min_rrr", 1.20))
        ticker_col = "ticker" if "ticker" in df.columns else ("asset" if "asset" in df.columns else ("symbol" if "symbol" in df.columns else None))
        if ticker_col is None:
            return orders
        for row in df.to_dicts():
            side = str(row.get("side") or row.get("candidate_signal") or "").upper()
            if side not in ("BUY", "LONG"):
                continue
            conf = float(row.get("prediction_probability") or row.get("probability") or 0.0)
            if conf < min_conf:
                continue
            entry = float(row.get("entry_price") or row.get("current_price") or row.get("close") or 0.0)
            tp = float(row.get("tp_price") or row.get("take_profit") or 0.0)
            sl = float(row.get("sl_price") or row.get("stop_loss") or 0.0)
            if entry <= 0 or tp <= entry or sl <= 0 or sl >= entry:
                continue
            rrr = (tp - entry) / (entry - sl) if (entry - sl) > 0 else 0
            if rrr < min_rrr:
                continue
            t = str(row.get(ticker_col) or "").strip()
            if not t.endswith(".JK"):
                t = f"{t}.JK"
            orders.append({
                "ticker": t,
                "symbol": t,
                "direction": "BUY",
                "entry_price": entry,
                "tp_price": tp,
                "sl_price": sl,
                "probability": conf,
                "risk_reward_ratio": rrr,
                "horizon": normalize_horizon(row.get("horizon")),
                "timestamp": str(row.get("timestamp") or utc_now()),
                "reason": str(row.get("reason") or row.get("signal_reason") or "Rule-based"),
            })
        return orders

    def _signals_to_orders(self, df: pl.DataFrame) -> List[Dict[str, Any]]:
        if df is None or df.height == 0:
            return []
        # Prefer validated rows
        if "is_valid_execution" in df.columns:
            df = df.filter(pl.col("is_valid_execution").fill_null(False) == True)
        elif "signal_valid" in df.columns:
            df = df.filter(pl.col("signal_valid").fill_null(False) == True)
        return self._predictions_to_orders(df)

    def _latest_prices_from_market(self) -> Dict[str, float]:
        prices: Dict[str, float] = {}
        src = self.market_data if self.market_data.height else self.features_data
        if src is None or src.height == 0:
            return prices
        tcol = "ticker" if "ticker" in src.columns else ("asset" if "asset" in src.columns else None)
        if tcol is None or "close" not in src.columns:
            return prices
        try:
            last = src.sort("timestamp" if "timestamp" in src.columns else ("date" if "date" in src.columns else tcol)).group_by(tcol).tail(1)
            for row in last.to_dicts():
                t = str(row.get(tcol, ""))
                if t and not t.endswith(".JK"):
                    t = f"{t}.JK"
                px = float(row.get("close") or 0.0)
                if t and px > 0:
                    prices[t] = px
                    prices[t.replace(".JK", "")] = px
        except Exception as e:
            logger.warning(f"⚠️ latest_prices build failed: {e}")
        return prices

    def _apply_simulated_tpsl_exits(self, prices: Dict[str, float]) -> None:
        if not self.portfolio_engine or not prices:
            return
        try:
            positions = dict(getattr(self.portfolio_engine, "positions", {}) or {})
        except Exception:
            return
        for sym, pos in list(positions.items()):
            status = str(pos.get("status", "ACTIVE")).upper()
            if status not in ("ACTIVE", "OPEN"):
                continue
            px = float(prices.get(sym) or prices.get(sym.replace(".JK", "")) or 0.0)
            if px <= 0:
                continue
            tp = float(pos.get("tp_price") or pos.get("take_profit") or 0.0)
            sl = float(pos.get("sl_price") or pos.get("stop_loss") or 0.0)
            if tp <= 0 or sl <= 0:
                continue
            if px >= tp:
                reason = "CLOSED_TP"
            elif px <= sl:
                reason = "CLOSED_SL"
            else:
                continue
            try:
                eng = getattr(self.portfolio_engine, "execution_engine", None)
                if eng and hasattr(eng, "execute_sell"):
                    eng.execute_sell(sym, current_price=px, reason=reason)
                    logger.info(f"🏁 [{reason}] {sym} @ {px:.2f}")
            except Exception as e:
                logger.warning(f"⚠️ TP/SL exit failed for {sym}: {e}")

    def utc_now(self) -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # ========================== MAIN RUN ==========================

    def run(self) -> None:
        logger.info("=" * 60)
        logger.info("🚀 IDX SIMULATION PIPELINE — S.E.A. Master Entity | SIMULATION_ONLY")
        logger.info(f"   execution_id={self.execution_id}")
        logger.info("=" * 60)
        try:
            self._step_0_sea_awaken()
            self._step_1_universe()
            self._step_2_data()
            self._step_3_sea_config()
            self._step_4_features()
            self._step_5_ml()
            self._step_6_prediction_engine()
            self._step_7_sea_analysis()
            self._step_8_signals()
            self._step_9_risk()
            self._step_10_portfolio_simulation()
            self._step_11_storage()
            self._step_12_sea_telegram()
            self._step_13_monitoring_eval()
            self._step_14_self_learning()
            self._step_15_autonomous_agent()
            logger.info("=" * 60)
            logger.info(
                f"🎉 PIPELINE COMPLETE | orders={len(self.orders)} | "
                f"configured_by={self.trading_config.get('configured_by')}"
            )
            logger.info("=" * 60)
        except Exception as e:
            logger.error(f"💥 Fatal pipeline error: {e}\n{traceback.format_exc()}")
            sys.exit(1)


# ========================== CLI ENTRY POINT ==========================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="IDX Simulated Scalping Engine — S.E.A. Master Orchestrator"
    )
    parser.add_argument("--dry-run", action="store_true", help="Paper/simulation run")
    parser.add_argument("--self-learning", action="store_true", help="Enable full self-learning")
    parser.add_argument("--bootstrap-universe", action="store_true", help="Write default universe.json")
    parser.add_argument("--reset-dryrun", action="store_true", help="Reset local simulation state")
    parser.add_argument("--health-check", action="store_true", help="Run health check only")
    parser.add_argument("--enable-self-evolving", action="store_true",
                        help="Activate S.E.A. Master with full autonomous evolution")

    args = parser.parse_args()

    if args.bootstrap_universe:
        if HAS_DATA and sanitize_ticker_list is not None:
            universe = sanitize_ticker_list(DEFAULT_BLUECHIP_UNIVERSE)
        else:
            universe = DEFAULT_BLUECHIP_UNIVERSE
        with open(DEFAULT_UNIVERSE_FILE, "w", encoding="utf-8") as f:
            json.dump(universe, f, indent=2)
        print(f"✅ universe.json created with {len(universe)} tickers")
        sys.exit(0)

    if args.reset_dryrun:
        for rel in ("data/storage_dryrun.db", "storage_dryrun.db", "autonomous_engine.db"):
            if os.path.exists(rel):
                try:
                    os.unlink(rel)
                    print(f"🗑️ Removed {rel}")
                except Exception as e:
                    print(f"⚠️ Could not remove {rel}: {e}")
        sys.exit(0)

    orchestrator = ProductionOrchestrator(
        dry_run=True,
        self_learning=args.self_learning,
        enable_self_evolving=args.enable_self_evolving,
    )

    if args.health_check:
        orchestrator._log_module_matrix()
        if orchestrator.self_evolving_agent:
            orchestrator.self_evolving_agent.boot()
            print("✅ Health check passed.")
        else:
            print("⚠️ Agent not available.")
    else:
        orchestrator.run()
